### ISSUE TITLE
Use single version name in build.gradle (foremWebView) file

### ISSUE THREAD

**Issue by rt4914** [forem/ForemWebView-android#21]
Currently in `build.gradle` of `foremWebView` file we are using `versionName` at three places separately. Instead it should be a single variable which should be used at all places.

The three places where this versionName is getting used are:
https://github.com/forem/ForemWebView-android/blob/008b511a2280a2bf2a433d29817714fd7fe08f47/foremwebview/build.gradle#L14

https://github.com/forem/ForemWebView-android/blob/008b511a2280a2bf2a433d29817714fd7fe08f47/foremwebview/build.gradle#L17

https://github.com/forem/ForemWebView-android/blob/008b511a2280a2bf2a433d29817714fd7fe08f47/foremwebview/build.gradle#L68

**Comment by Chandra-Sekhar-Bala** [comment]
Hey, @rt4914 I want to work on this, but I don't understand this properly. Like ```versionName``` is used only once here. Maybe I'm wrong or something. 
p.s: Looking forward to any suggestion or resource. 

<img width="706" alt="Forem" src="https://user-images.githubusercontent.com/57448981/179848101-37ee9cd4-5621-4e2e-af89-8a4c18b6516a.png">

**Comment by rt4914** [comment]
@Chandra-Sekhar-Bala Thanks for showing interest.
I have updated the description to mention all the places where the value of versionName is getting used.

We need to create a variable such that at all these three places we can actually use that variable directly.

**Comment by Chandra-Sekhar-Bala** [comment]
Thanks for that, I'm on it.
